mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsBottom/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_ResistancesTop/Plots
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsBottom/Plots

mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsBottom//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_ResistancesTop//Plots/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsBottom//Plots/temp

mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsBottom/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_ResistancesTop/Plots/Histo
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsBottom/Plots/Histo

mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Cs137_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th232_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Co60_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/K40_CapacitorsBottom/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Ra226_CapacitorsTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/Th228_ResistancesTop/Plots/Histo/temp
mkdir ~/cristian/RPE_IAXO/data/IAXOD0/Argon_AGET_halfway/U238_CapacitorsBottom/Plots/Histo/temp