#!/bin/bash
sbatch restManagerSimToAnaTrackK40Chip_halfway.sh

sbatch restManagerSimToAnaTrackTh228Chip_halfway.sh

sbatch restManagerSimToAnaTrackRa226Chip_halfway.sh

sbatch restManagerSimToAnaTrackRa228Chip_halfway.sh

sbatch restManagerSimToAnaTrackU238Chip_halfway.sh