#!bin/bash

sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh
sbatch restG4U238FromCapacitorsBottom_halfway.sh

sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh
sbatch restG4Th232FromCapacitorsBottom_halfway.sh